### ISSUE TITLE
Upside down text

### ISSUE THREAD

**Issue by DavidWhaleMEF** [makecode-extensions/ScrollText#1]
We have a user interested in upside down text - could your package do this in the future, do you think? e.g. hang the micro:bit upside down from a necklace, the text needs to be inverted.

**Comment by DavidWhaleMEF** [comment]
It looks like SCROLL_ROTATE 180 will do this, I will pass it on to the user.

![screen shot 2018-09-14 at 09 32 34](https://user-images.githubusercontent.com/25079586/45539305-3779b000-b801-11e8-9434-c1832b573280.png)

**Comment by shaoziyang** [comment]
Yes, default value of rotate is not correctly, it should be I have fixed it. Thank you.
