### ISSUE TITLE
micro:bit error 844

### ISSUE THREAD

**Issue by JozKov** [makecode-extensions/ScrollText#3]
Hi shaoziyang,
if I want to run some program with ScrollText (f.e. showNumber(7, down, 270, 100)), my BBC micro:bit (hardware ver1.5, firmware ver0253) show error 844, wich means: GC allocation failed for requested number of bytes. 
This error is only in reality, not in Microsoft MakeCode. I tested your extension direcrtly from MakeCode and from Github, but error is the same. 
Please fix error.

**Comment by shaoziyang** [comment]
It is cause by makecode V2's new memory manager, it works in makecode v1.
https://makecode.microbit.org/v1

I will fixed it soon.

**Comment by shaoziyang** [comment]
v1.4.0 works in makecode v2 now.

**Comment by JozKov** [comment]
Hi shaoziyang,
your ScrollText works correctly now. Thank you for fixing error so quick.
Have a nice day.
